---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-athena-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - athena.services.k8s.aws
  resources:
  - workgroups
  verbs:
  - get
  - list
  - watch
