# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS Athena controller is a service controller for managing Athena resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Athena
description: |-
  Manage Amazon Athena resources in AWS from within your Kubernetes cluster.


  **About Amazon Athena**


  Amazon Athena is an interactive query service that makes it easy to analyze data directly in Amazon Simple Storage Service (Amazon S3)
  using standard SQL. With a few actions in the AWS Management Console, you can point Athena at your data stored in Amazon S3 and 
  begin using standard SQL to run ad-hoc queries and get results in seconds.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: WorkGroup
  spec: '{}'
maintainers:
- name: "athena maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon Athena Developer Resources
  url: https://aws.amazon.com/athena/resources/
